env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  complexity:
    - error
    - 5
  max-depth:
    - error
    - 2
  eqeqeq: error
  no-eq-null: error
  no-implicit-coercion: error
  max-lines-per-function:
    - error
    - 50
overrides:
  - files:
      - '*.spec.js'
    rules:
      max-lines-per-function: off
